# Generated by Django 2.2.4 on 2019-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_projectdone_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
